import { readFileSync, writeFileSync } from 'node:fs';
import { bootstrapApplication, provideClientHydration } from '@angular/platform-browser';
import { renderApplication } from '@angular/platform-server';

import { SsrFixtureComponent } from './ssr-fixture';

const FIXTURE_PATH =
  'projects/libraries/streamix/angular/src/tests/ssr/ssr-html.ts';

/**
 * Renders the fixture the way a real SSR build does: through
 * `renderApplication`, which sets `ngServerMode` and emits the hydration
 * annotations the client needs.
 */
async function renderFixture(): Promise<string> {
  return renderApplication(
    context =>
      bootstrapApplication(
        SsrFixtureComponent,
        { providers: [provideClientHydration()] },
        context,
      ),
    {
      document: '<sx-ssr-fixture></sx-ssr-fixture>',
      url: 'http://localhost/',
      allowedHosts: ['localhost'],
    },
  );
}

/**
 * Server-rendering contract for the compiled view: the marker element stays in
 * place with the block content inside it, no listener is attached, and the
 * two-way value is rendered so hydration finds it.
 */
describe('compiled view under server rendering', () => {
  it('keeps the committed server HTML fixture in sync', async () => {
    const contents =
      '// Generated by ssr-render.spec.ts — rerun with STREAMIX_UPDATE_FIXTURES=1 to refresh.\n' +
      `export const SSR_FIXTURE_HTML = ${JSON.stringify(await renderFixture())};\n`;

    if (process.env['STREAMIX_UPDATE_FIXTURES'] === '1') {
      writeFileSync(FIXTURE_PATH, contents);
      return;
    }

    expect(readFileSync(FIXTURE_PATH, 'utf8')).toBe(contents);
  });

  it('keeps empty markers and renders the rest of the template', async () => {
    const html = await renderFixture();

    // The marker is kept and stays empty: the client's template declares an
    // empty marker, so block content rendered inside it would make hydration
    // mismatch. The compiled view fills it right after hydration.
    expect(html).toMatch(/<span data-sx-block="0" data-slot="if"><\/span>/);
    expect(html).toMatch(/<span data-sx-block="1" data-slot="for"><\/span>/);
    expect(html).not.toContain('<strong>');
    expect(html).not.toContain('<li>');

    // Everything the compiler binds as a direct DOM write still renders
    // through Angular's SSR fallback.
    expect(html).toContain('value="hello"');
    expect(html).toContain('<button type="button">click</button>');
  });

  it('attaches no event listeners while rendering on the server', async () => {
    const addListener = spyOn(EventTarget.prototype, 'addEventListener');
    await renderFixture();

    expect(addListener).not.toHaveBeenCalled();
  });

  it('renders the two-way value into the input', async () => {
    const html = await renderFixture();

    expect(html).toContain('value="hello"');
  });
});
